/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as ProcumentIndexRouteImport } from './routes/procument/index'
import { Route as HodIndexRouteImport } from './routes/hod/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as CeoIndexRouteImport } from './routes/ceo/index'
import { Route as UserQuotationRouteImport } from './routes/user/quotation'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserHistoryRouteImport } from './routes/user/history'
import { Route as UserDepartmentRouteImport } from './routes/user/department'
import { Route as UserCalendarRouteImport } from './routes/user/calendar'
import { Route as UserBudgetRouteImport } from './routes/user/budget'
import { Route as ProcumentSettingsRouteImport } from './routes/procument/settings'
import { Route as ProcumentQuotationsRouteImport } from './routes/procument/quotations'
import { Route as HodSettingsRouteImport } from './routes/hod/settings'
import { Route as HodReportsRouteImport } from './routes/hod/reports'
import { Route as HodCalendarRouteImport } from './routes/hod/calendar'
import { Route as HodApprovalRouteImport } from './routes/hod/approval'
import { Route as FinanceSettingsRouteImport } from './routes/finance/settings'
import { Route as FinanceRequestRouteImport } from './routes/finance/request'
import { Route as CeoSettingsRouteImport } from './routes/ceo/settings'
import { Route as FinanceRequestIdRouteImport } from './routes/finance/request_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcumentIndexRoute = ProcumentIndexRouteImport.update({
  id: '/procument/',
  path: '/procument/',
  getParentRoute: () => rootRouteImport,
} as any)
const HodIndexRoute = HodIndexRouteImport.update({
  id: '/hod/',
  path: '/hod/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/ceo/',
  path: '/ceo/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuotationRoute = UserQuotationRouteImport.update({
  id: '/user/quotation',
  path: '/user/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/user/history',
  path: '/user/history',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDepartmentRoute = UserDepartmentRouteImport.update({
  id: '/user/department',
  path: '/user/department',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCalendarRoute = UserCalendarRouteImport.update({
  id: '/user/calendar',
  path: '/user/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBudgetRoute = UserBudgetRouteImport.update({
  id: '/user/budget',
  path: '/user/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcumentSettingsRoute = ProcumentSettingsRouteImport.update({
  id: '/procument/settings',
  path: '/procument/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcumentQuotationsRoute = ProcumentQuotationsRouteImport.update({
  id: '/procument/quotations',
  path: '/procument/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const HodSettingsRoute = HodSettingsRouteImport.update({
  id: '/hod/settings',
  path: '/hod/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HodReportsRoute = HodReportsRouteImport.update({
  id: '/hod/reports',
  path: '/hod/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HodCalendarRoute = HodCalendarRouteImport.update({
  id: '/hod/calendar',
  path: '/hod/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const HodApprovalRoute = HodApprovalRouteImport.update({
  id: '/hod/approval',
  path: '/hod/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: '/finance/settings',
  path: '/finance/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRequestRoute = FinanceRequestRouteImport.update({
  id: '/finance/request',
  path: '/finance/request',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoSettingsRoute = CeoSettingsRouteImport.update({
  id: '/ceo/settings',
  path: '/ceo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRequestIdRoute = FinanceRequestIdRouteImport.update({
  id: '/finance/request_/$id',
  path: '/finance/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo/settings': typeof CeoSettingsRoute
  '/finance/request': typeof FinanceRequestRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/hod/approval': typeof HodApprovalRoute
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/procument/quotations': typeof ProcumentQuotationsRoute
  '/procument/settings': typeof ProcumentSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/history': typeof UserHistoryRoute
  '/user/profile': typeof UserProfileRoute
  '/user/quotation': typeof UserQuotationRoute
  '/ceo/': typeof CeoIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/hod/': typeof HodIndexRoute
  '/procument/': typeof ProcumentIndexRoute
  '/user/': typeof UserIndexRoute
  '/finance/request/$id': typeof FinanceRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo/settings': typeof CeoSettingsRoute
  '/finance/request': typeof FinanceRequestRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/hod/approval': typeof HodApprovalRoute
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/procument/quotations': typeof ProcumentQuotationsRoute
  '/procument/settings': typeof ProcumentSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/history': typeof UserHistoryRoute
  '/user/profile': typeof UserProfileRoute
  '/user/quotation': typeof UserQuotationRoute
  '/ceo': typeof CeoIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/hod': typeof HodIndexRoute
  '/procument': typeof ProcumentIndexRoute
  '/user': typeof UserIndexRoute
  '/finance/request/$id': typeof FinanceRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ceo/settings': typeof CeoSettingsRoute
  '/finance/request': typeof FinanceRequestRoute
  '/finance/settings': typeof FinanceSettingsRoute
  '/hod/approval': typeof HodApprovalRoute
  '/hod/calendar': typeof HodCalendarRoute
  '/hod/reports': typeof HodReportsRoute
  '/hod/settings': typeof HodSettingsRoute
  '/procument/quotations': typeof ProcumentQuotationsRoute
  '/procument/settings': typeof ProcumentSettingsRoute
  '/user/budget': typeof UserBudgetRoute
  '/user/calendar': typeof UserCalendarRoute
  '/user/department': typeof UserDepartmentRoute
  '/user/history': typeof UserHistoryRoute
  '/user/profile': typeof UserProfileRoute
  '/user/quotation': typeof UserQuotationRoute
  '/ceo/': typeof CeoIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/hod/': typeof HodIndexRoute
  '/procument/': typeof ProcumentIndexRoute
  '/user/': typeof UserIndexRoute
  '/finance/request_/$id': typeof FinanceRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ceo/settings'
    | '/finance/request'
    | '/finance/settings'
    | '/hod/approval'
    | '/hod/calendar'
    | '/hod/reports'
    | '/hod/settings'
    | '/procument/quotations'
    | '/procument/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/history'
    | '/user/profile'
    | '/user/quotation'
    | '/ceo/'
    | '/finance/'
    | '/hod/'
    | '/procument/'
    | '/user/'
    | '/finance/request/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ceo/settings'
    | '/finance/request'
    | '/finance/settings'
    | '/hod/approval'
    | '/hod/calendar'
    | '/hod/reports'
    | '/hod/settings'
    | '/procument/quotations'
    | '/procument/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/history'
    | '/user/profile'
    | '/user/quotation'
    | '/ceo'
    | '/finance'
    | '/hod'
    | '/procument'
    | '/user'
    | '/finance/request/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ceo/settings'
    | '/finance/request'
    | '/finance/settings'
    | '/hod/approval'
    | '/hod/calendar'
    | '/hod/reports'
    | '/hod/settings'
    | '/procument/quotations'
    | '/procument/settings'
    | '/user/budget'
    | '/user/calendar'
    | '/user/department'
    | '/user/history'
    | '/user/profile'
    | '/user/quotation'
    | '/ceo/'
    | '/finance/'
    | '/hod/'
    | '/procument/'
    | '/user/'
    | '/finance/request_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CeoSettingsRoute: typeof CeoSettingsRoute
  FinanceRequestRoute: typeof FinanceRequestRoute
  FinanceSettingsRoute: typeof FinanceSettingsRoute
  HodApprovalRoute: typeof HodApprovalRoute
  HodCalendarRoute: typeof HodCalendarRoute
  HodReportsRoute: typeof HodReportsRoute
  HodSettingsRoute: typeof HodSettingsRoute
  ProcumentQuotationsRoute: typeof ProcumentQuotationsRoute
  ProcumentSettingsRoute: typeof ProcumentSettingsRoute
  UserBudgetRoute: typeof UserBudgetRoute
  UserCalendarRoute: typeof UserCalendarRoute
  UserDepartmentRoute: typeof UserDepartmentRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserProfileRoute: typeof UserProfileRoute
  UserQuotationRoute: typeof UserQuotationRoute
  CeoIndexRoute: typeof CeoIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  HodIndexRoute: typeof HodIndexRoute
  ProcumentIndexRoute: typeof ProcumentIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  FinanceRequestIdRoute: typeof FinanceRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procument/': {
      id: '/procument/'
      path: '/procument'
      fullPath: '/procument/'
      preLoaderRoute: typeof ProcumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/': {
      id: '/hod/'
      path: '/hod'
      fullPath: '/hod/'
      preLoaderRoute: typeof HodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/ceo'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/quotation': {
      id: '/user/quotation'
      path: '/user/quotation'
      fullPath: '/user/quotation'
      preLoaderRoute: typeof UserQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/history': {
      id: '/user/history'
      path: '/user/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/department': {
      id: '/user/department'
      path: '/user/department'
      fullPath: '/user/department'
      preLoaderRoute: typeof UserDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/calendar': {
      id: '/user/calendar'
      path: '/user/calendar'
      fullPath: '/user/calendar'
      preLoaderRoute: typeof UserCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/budget': {
      id: '/user/budget'
      path: '/user/budget'
      fullPath: '/user/budget'
      preLoaderRoute: typeof UserBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procument/settings': {
      id: '/procument/settings'
      path: '/procument/settings'
      fullPath: '/procument/settings'
      preLoaderRoute: typeof ProcumentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procument/quotations': {
      id: '/procument/quotations'
      path: '/procument/quotations'
      fullPath: '/procument/quotations'
      preLoaderRoute: typeof ProcumentQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/settings': {
      id: '/hod/settings'
      path: '/hod/settings'
      fullPath: '/hod/settings'
      preLoaderRoute: typeof HodSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/reports': {
      id: '/hod/reports'
      path: '/hod/reports'
      fullPath: '/hod/reports'
      preLoaderRoute: typeof HodReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/calendar': {
      id: '/hod/calendar'
      path: '/hod/calendar'
      fullPath: '/hod/calendar'
      preLoaderRoute: typeof HodCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod/approval': {
      id: '/hod/approval'
      path: '/hod/approval'
      fullPath: '/hod/approval'
      preLoaderRoute: typeof HodApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/settings': {
      id: '/finance/settings'
      path: '/finance/settings'
      fullPath: '/finance/settings'
      preLoaderRoute: typeof FinanceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/request': {
      id: '/finance/request'
      path: '/finance/request'
      fullPath: '/finance/request'
      preLoaderRoute: typeof FinanceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo/settings': {
      id: '/ceo/settings'
      path: '/ceo/settings'
      fullPath: '/ceo/settings'
      preLoaderRoute: typeof CeoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/request_/$id': {
      id: '/finance/request_/$id'
      path: '/finance/request/$id'
      fullPath: '/finance/request/$id'
      preLoaderRoute: typeof FinanceRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CeoSettingsRoute: CeoSettingsRoute,
  FinanceRequestRoute: FinanceRequestRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
  HodApprovalRoute: HodApprovalRoute,
  HodCalendarRoute: HodCalendarRoute,
  HodReportsRoute: HodReportsRoute,
  HodSettingsRoute: HodSettingsRoute,
  ProcumentQuotationsRoute: ProcumentQuotationsRoute,
  ProcumentSettingsRoute: ProcumentSettingsRoute,
  UserBudgetRoute: UserBudgetRoute,
  UserCalendarRoute: UserCalendarRoute,
  UserDepartmentRoute: UserDepartmentRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserProfileRoute: UserProfileRoute,
  UserQuotationRoute: UserQuotationRoute,
  CeoIndexRoute: CeoIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  HodIndexRoute: HodIndexRoute,
  ProcumentIndexRoute: ProcumentIndexRoute,
  UserIndexRoute: UserIndexRoute,
  FinanceRequestIdRoute: FinanceRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
